-- ============================================================
-- Mishthi Sattva — database schema
-- Run once in the Supabase SQL editor (SQL Editor → New query → Run).
--
-- SECURITY NOTE: the anon key is public (it ships in the browser), so every
-- policy below assumes an untrusted caller. Visitors may READ the catalogue
-- and CREATE orders/enquiries, but may not read other people's orders or
-- edit the catalogue. Admin writes require a logged-in Supabase user.
-- ============================================================

create extension if not exists "pgcrypto";

-- ------------------------------------------------------------
-- 1. PRODUCTS  (catalogue — public read, admin write)
-- ------------------------------------------------------------
create table if not exists products (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  slug        text unique,
  category    text not null,          -- ayurvedic | spices | hair | beauty | special
  price       numeric,                -- null = "Ask for price"
  mrp         numeric,
  weight      text,                   -- e.g. "500 g", "200 ml"
  short_desc  text,
  benefits    text[]  default '{}',
  photo       text,                   -- storage URL or /assets path
  gallery     text[]  default '{}',
  in_stock    boolean default true,
  featured    boolean default false,
  sort_order  int     default 0,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

-- ------------------------------------------------------------
-- 2. ORDERS  (checkout records — anyone may create, only admin may read)
--    Contains personal data (phone/address): NEVER publicly readable.
-- ------------------------------------------------------------
create table if not exists orders (
  id             uuid primary key default gen_random_uuid(),
  order_no       bigint generated by default as identity,
  customer_name  text not null,
  phone          text not null,
  address        text,
  city           text default 'Kotkapura',
  note           text,
  items          jsonb not null default '[]',   -- [{id,name,qty,price,weight}]
  subtotal       numeric not null default 0,
  delivery_fee   numeric not null default 0,
  total          numeric not null default 0,
  status         text    not null default 'new', -- new|confirmed|packed|delivered|cancelled
  source         text    not null default 'website',
  created_at     timestamptz default now()
);
create index if not exists orders_created_idx on orders (created_at desc);

-- ------------------------------------------------------------
-- 3. ENQUIRIES  (contact form — anyone may create, only admin may read)
-- ------------------------------------------------------------
create table if not exists enquiries (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  phone       text,
  message     text not null,
  status      text not null default 'new',       -- new|replied|closed
  created_at  timestamptz default now()
);
create index if not exists enquiries_created_idx on enquiries (created_at desc);

-- ------------------------------------------------------------
-- 4. REVIEWS  (only published ones are public — no fake reviews on the site)
-- ------------------------------------------------------------
create table if not exists reviews (
  id             uuid primary key default gen_random_uuid(),
  customer_name  text not null,
  city           text,
  product_name   text,
  rating         int check (rating between 1 and 5),
  quote          text not null,
  source         text,                            -- whatsapp | google | direct
  is_published   boolean default false,           -- admin approves before it shows
  created_at     timestamptz default now()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
alter table products   enable row level security;
alter table orders     enable row level security;
alter table enquiries  enable row level security;
alter table reviews    enable row level security;

-- ---- products: world-readable, admin-writable ----
drop policy if exists products_public_read on products;
create policy products_public_read on products
  for select using (true);

drop policy if exists products_admin_write on products;
create policy products_admin_write on products
  for all to authenticated using (true) with check (true);

-- ---- orders: anyone may place one; only admins may read them ----
drop policy if exists orders_public_insert on orders;
create policy orders_public_insert on orders
  for insert with check (true);

drop policy if exists orders_admin_read on orders;
create policy orders_admin_read on orders
  for select to authenticated using (true);

drop policy if exists orders_admin_update on orders;
create policy orders_admin_update on orders
  for update to authenticated using (true) with check (true);

-- ---- enquiries: anyone may submit; only admins may read ----
drop policy if exists enquiries_public_insert on enquiries;
create policy enquiries_public_insert on enquiries
  for insert with check (true);

drop policy if exists enquiries_admin_read on enquiries;
create policy enquiries_admin_read on enquiries
  for select to authenticated using (true);

drop policy if exists enquiries_admin_update on enquiries;
create policy enquiries_admin_update on enquiries
  for update to authenticated using (true) with check (true);

-- ---- reviews: public sees only approved ones ----
drop policy if exists reviews_public_read on reviews;
create policy reviews_public_read on reviews
  for select using (is_published = true);

drop policy if exists reviews_admin_all on reviews;
create policy reviews_admin_all on reviews
  for all to authenticated using (true) with check (true);

-- ============================================================
-- STORAGE: product photos (public read, admin write)
-- ============================================================
insert into storage.buckets (id, name, public)
values ('product-photos', 'product-photos', true)
on conflict (id) do nothing;

drop policy if exists ms_photos_read on storage.objects;
create policy ms_photos_read on storage.objects
  for select using (bucket_id = 'product-photos');

drop policy if exists ms_photos_write on storage.objects;
create policy ms_photos_write on storage.objects
  for all to authenticated
  using (bucket_id = 'product-photos' and is_admin())
  with check (bucket_id = 'product-photos' and is_admin());

-- ============================================================
-- AFTER RUNNING THIS:
--   1. Authentication → Users → "Add user" to create the admin login
--      (that account is what "to authenticated" above unlocks).
--   2. Products are seeded separately from the existing catalogue.
-- ============================================================
