/* Mishthi Sattva — Shop catalogue (instant-load snapshot).
   AUTO-GENERATED from the live Supabase 'products' table by scripts/sync-catalogue.mjs.
   Do not hand-edit product prices here — change them in the admin panel, then run
   `npm run sync` to regenerate this file. Presentation extras (rating, reviews,
   tags, badge, long desc) are preserved per product across syncs.
   Exposes window.MSShopData. */

const MS_CATEGORIES = [
  { id: "sweetness-with-wellness", name: "Sweetness with Wellness", tint: "color-mix(in oklab, var(--forest) 55%, var(--gold))" },
  { id: "sip", name: "Sattvic Sip", tint: "var(--forest)" },
  { id: "immunity", name: "Immunity Booster", tint: "color-mix(in oklab, var(--forest) 55%, var(--gold))" },
  { id: "bodycare", name: "Sattvic Body Care", tint: "var(--gold-soft)" },
  { id: "masala-premix", name: "Masala & Premix", tint: "var(--gold-soft)" },
  { id: "munching", name: "Munching", tint: "var(--gold)" },
  { id: "ms-special", name: "MS Special", tint: "var(--forest-deep)" },
  { id: "pickle-murabba", name: "Handcrafted Pickles", tint: "var(--gold)" },
];

const MS_PRODUCTS = [
  // ---- Sweetness with Wellness ----
  { id: "alsi-laddu", name: "Alsi Laddu", cat: "sweetness-with-wellness", price: 220, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "https://wiuokqmggxkonxvzrnsb.supabase.co/storage/v1/object/public/product-photos/alsi-laddu-1789198390588.png",
    desc: "A delicious traditional laddu made with the goodness of Alsi (flax seeds). Naturally rich in wholesome nutrients, this laddu offers a delightful combination of nutty flavour and traditional nourishment to our knees, back and joints.",
    facts: [],
    variants: [{"weight":"100 GM","price":220,"mrp":350},{"weight":"250 GM","price":450,"mrp":600},{"weight":"500 GM","price":850,"mrp":1200},{"weight":"1 KG","price":1650,"mrp":2200}],
    long_desc: "A delicious traditional laddu made with the goodness of Alsi (flax seeds). Naturally rich in wholesome nutrients, this laddu offers a delightful combination of nutty flavour and traditional nourishment to our knees, back and joints.",
    wellness_benefits: [{"text":"","title":"•\tNaturally contains omega-3 fatty acids •\tNurture our heart and joints •\tA source of dietary fibre •\tContains healthy fats •\tMakes for a wholesome and satisfying snack"}],
    ingredients: ["Alsi (flax seeds), wheat flour, ghee, and other carefully selected traditional ingredients and ayurvedic spices."],
    storage_info: "Store in an airtight container in a cool and dry place, away from sunlight and moisture.",
    promise: ["Wholesome traditional ingredients, carefully prepared to preserve authentic flavour and goodness."] },
  { id: "besan-gond-laddu", name: "Besan Gond Laddu", cat: "sweetness-with-wellness", price: 220, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A timeless traditional sweet made with roasted besan and edible gond. Rich, aromatic and deeply satisfying, our Besan Gond Laddu brings the warmth and comfort of authentic homemade Indian sweets.",
    facts: [],
    variants: [{"weight":"100 GM","price":220,"mrp":350},{"weight":"250 GM","price":450,"mrp":600},{"weight":"500 GM","price":850,"mrp":1200},{"weight":"1 KG","price":1650,"mrp":2200}],
    long_desc: "A timeless traditional sweet made with roasted besan and edible gond. Rich, aromatic and deeply satisfying, our Besan Gond Laddu brings the warmth and comfort of authentic homemade Indian sweets.",
    wellness_benefits: [{"text":"","title":"•\tProvides wholesome energy •\tContains naturally occurring nutrients from gram flour •\tTraditionally enjoyed for nourishment •\tA satisfying and comforting sweet •\tKids best tiffin treat for overall immunity"}],
    ingredients: ["Besan (gram flour), edible gond, natural sweetening ingredients, ghee, nuts and other carefully selected ingredients as per the Mishthi Sattva recipe."],
    storage_info: "Store in an airtight container in a cool and dry place. Keep away from moisture.",
    promise: ["Authentic traditional preparation, carefully roasted ingredients and premium quality in every laddu."] },
  { id: "japa-laddu", name: "Japa Laddu", cat: "sweetness-with-wellness", price: 220, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "Inspired by traditional postpartum nourishment, Japa Laddu is thoughtfully prepared using time-honoured ingredients traditionally enjoyed during the post-delivery period. A delicious blend of warmth, nourishment and traditional wisdom, which helps new mother in lactation effectively.",
    facts: [],
    variants: [{"weight":"100 GM","price":220,"mrp":350},{"weight":"250 GM","price":450,"mrp":600},{"weight":"500 GM","price":850,"mrp":1200},{"weight":"1 KG","price":1650,"mrp":2200}],
    long_desc: "Inspired by traditional postpartum nourishment, Japa Laddu is thoughtfully prepared using time-honoured ingredients traditionally enjoyed during the post-delivery period. A delicious blend of warmth, nourishment and traditional wisdom, which helps new mother in lactation effectively.",
    wellness_benefits: [{"text":"","title":"•\tTraditionally enjoyed as part of postpartum nourishment •\tProvides wholesome energy •\tContains nourishing traditional ingredients •\tSupports a balanced and nourishing diet during the postpartum period •\tSupports in lactation journey happier •\tWorks on body pains and immunity"}],
    ingredients: ["Prepared using traditional postpartum ingredients such as nuts, seeds, gond and other recipe-specific nourishing ingredients and ayurvedic spices."],
    storage_info: "Store in an airtight container in a cool and dry place. Follow recommended storage instructions for maximum freshness.",
    promise: ["Inspired by traditional Indian postpartum food wisdom and prepared with carefully selected ingredients and exceptional care."] },
  { id: "japa-panjeeri", name: "Japa Panjeeri", cat: "sweetness-with-wellness", price: 220, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A traditional nourishing blend inspired by the age-old practice of preparing wholesome foods during the postpartum period. Japa Panjeeri brings together carefully selected ingredients in a delicious and comforting form.",
    facts: [],
    variants: [{"weight":"100 GM","price":220,"mrp":350},{"weight":"250 GM","price":450,"mrp":600},{"weight":"500 GM","price":850,"mrp":1200},{"weight":"1 KG","price":1650,"mrp":2200}],
    long_desc: "A traditional nourishing blend inspired by the age-old practice of preparing wholesome foods during the postpartum period. Japa Panjeeri brings together carefully selected ingredients in a delicious and comforting form.",
    wellness_benefits: [{"text":"","title":"•\tTraditionally consumed as part of postpartum nourishment •\tSupports in lactation journey happier •\tWorks on body pains and immunity •\tProvides wholesome energy •\tContains naturally occurring nutrients from nuts and seeds •\tA comforting and satisfying traditional food"}],
    ingredients: ["A traditional blend of selected ingredients such as whole wheat flour, nuts, seeds, edible gum, pure homemade ghee and other recipe-specific components from our Ayurveda"],
    storage_info: "Store in an airtight container in a cool and dry place. Always use a clean and dry spoon.",
    promise: ["Prepared with traditional inspiration, premium ingredients and the care associated with homemade nourishment."] },
  { id: "millets-laddu", name: "Millets Laddu", cat: "sweetness-with-wellness", price: 220, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A modern take on traditional goodness, our Millets Laddu brings the wholesome qualities of millets into a delicious and convenient sweet. Thoughtfully crafted for those seeking nutritious choices without giving up on taste.",
    facts: [],
    variants: [{"weight":"100 GM","price":220,"mrp":350},{"weight":"250 GM","price":450,"mrp":600},{"weight":"500 GM","price":850,"mrp":1200},{"weight":"1 KG","price":1650,"mrp":2200}],
    long_desc: "A modern take on traditional goodness, our Millets Laddu brings the wholesome qualities of millets into a delicious and convenient sweet. Thoughtfully crafted for those seeking nutritious choices without giving up on taste.",
    wellness_benefits: [{"text":"","title":"•\tMade with nutrient-rich millets •\tNaturally contains dietary fibre •\tProvides wholesome energy •\tA delicious alternative to refined flour-based sweets •\tSupports a balanced and mindful lifestyle •\tCan say haemoglobin or Calcium Laddu"}],
    ingredients: ["Selected millets like Ragi, Jwar, Baajra, Jaggary, nuts, seeds and spices according to weather."],
    storage_info: "Store in an airtight container in a cool, dry place. Keep away from direct sunlight and moisture.",
    promise: ["Thoughtfully crafted with wholesome ingredients and a commitment to bringing traditional grains into modern everyday eating."] },
  { id: "moong-dal-laddu", name: "Moong Dal Laddu", cat: "sweetness-with-wellness", price: 220, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A traditional delicacy prepared with the rich, comforting flavour of roasted moong dal. Smooth, aromatic and deliciously satisfying, this laddu combines authentic taste with wholesome ingredients.",
    facts: [],
    variants: [{"weight":"100 GM","price":220,"mrp":350},{"weight":"250 GM","price":450,"mrp":600},{"weight":"500 GM","price":850,"mrp":1200},{"weight":"1 KG","price":1650,"mrp":2200}],
    long_desc: "A traditional delicacy prepared with the rich, comforting flavour of roasted moong dal. Smooth, aromatic and deliciously satisfying, this laddu combines authentic taste with wholesome ingredients.",
    wellness_benefits: [{"text":"","title":"•\tContains naturally occurring plant-based protein •\tProvides wholesome energy •\tContains nutrients naturally found in moong dal •\tA satisfying traditional sweet •\tMeets protein intake •\tHelps eye health and vision"}],
    ingredients: ["Moong dal, natural sweetening ingredients, ghee, nuts and other selected ingredients according Ayurveda."],
    storage_info: "Store in an airtight container in a cool and dry place. Protect from moisture and direct sunlight.",
    promise: ["Made with carefully roasted ingredients to bring out the authentic flavour and aroma of traditional homemade sweets."] },
  { id: "protein-laddu", name: "Protein Laddu", cat: "sweetness-with-wellness", price: 220, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "Mishthi Sattva Protein Laddu is a wholesome homemade blend of roasted channa and soybean, gond, nuts, seeds, natural ingredients and pure ghee, crafted to provide nourishing protein and everyday energy. Made without refined sugar, refined oil, preservatives, artificial colours or flavours, these delicious laddus are perfect for children, women and the whole family. A delicious and wholesome way to add more protein-rich ingredients to your everyday diet. Our Protein Laddu combines nourishing ingredients with traditional taste, making it an ideal snack for an active and wellness-conscious lifestyle.",
    facts: [],
    variants: [{"weight":"100 GM","price":220,"mrp":350},{"weight":"250 GM","price":450,"mrp":600},{"weight":"500 GM","price":850,"mrp":1200},{"weight":"1 KG","price":1650,"mrp":2200}],
    long_desc: "Mishthi Sattva Protein Laddu is a wholesome homemade blend of roasted channa and soybean, gond, nuts, seeds, natural ingredients and pure ghee, crafted to provide nourishing protein and everyday energy. Made without refined sugar, refined oil, preservatives, artificial colours or flavours, these delicious laddus are perfect for children, women and the whole family. A delicious and wholesome way to add more protein-rich ingredients to your everyday diet. Our Protein Laddu combines nourishing ingredients with traditional taste, making it an ideal snack for an active and wellness-conscious lifestyle.",
    wellness_benefits: [{"text":"","title":"•\tContains protein-rich ingredients •\tSupports daily energy requirements •\tHelps make snacking more satisfying •\tA convenient and healthy tiffin snack •\tSuitable for active lifestyles"}],
    ingredients: ["Prepared using protein-rich ingredients like Roasted channa and roasted soybean along with a carefully balanced combination of wholesome traditional ingredients like gond, Desi Ghee, Mishri Powder or jaggary, Almonds, Cashews, Walnuts, Raisins, Pumpkin Seeds, Sunflower Seeds, melon seeds, watermelon seeds, Sesame Seeds, Flax Seeds and spices like white and black pepper, nutmeg to flavour."],
    storage_info: "Store in a cool and dry place in an airtight container. Keep away from moisture. Can be consumed upto 3 months, if refrigerated.",
    promise: ["A thoughtfully crafted combination of nourishment and taste, without compromising the authentic experience of a traditional laddu."] },
  { id: "punjabi-khoya-pinni", name: "Punjabi Khoya Pinni", cat: "sweetness-with-wellness", price: 220, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A rich and indulgent Punjabi classic and grandmothers’ specially crafted recipe with the comforting goodness of khoya made with dry coconut stuffed with poppy seeds and few secret traditional ingredients in milk. Our Punjabi Khoya Pinni celebrates authentic flavours, rich texture and the warmth of homemade sweets.",
    facts: [],
    variants: [{"weight":"100 GM","price":220,"mrp":350},{"weight":"250 GM","price":450,"mrp":600},{"weight":"500 GM","price":850,"mrp":1200},{"weight":"1 KG","price":1650,"mrp":2200}],
    long_desc: "A rich and indulgent Punjabi classic and grandmothers’ specially crafted recipe with the comforting goodness of khoya made with dry coconut stuffed with poppy seeds and few secret traditional ingredients in milk. Our Punjabi Khoya Pinni celebrates authentic flavours, rich texture and the warmth of homemade sweets.",
    wellness_benefits: [{"text":"","title":"•\tProvides energy from traditional ingredients •\tContains naturally occurring nutrients from milk and nuts •\tA satisfying and wholesome festive treat •\tMade with traditional ingredients and authentic flavours •\tCan helps in headache and back pains."}],
    ingredients: ["A carefully balanced combination of wholesome traditional ingredients like Milk, coconut, gond, Whole Wheat Atta, Desi Ghee, Mishri Powder or jaggary, Almonds, Cashews, Walnuts, Raisins, Pumpkin Seeds, Sunflower Seeds, melon seeds, watermelon seeds, Sesame Seeds, Flax Seeds poppy seeds and spices like white and black pepper, nutmeg, and some spices to flavour."],
    storage_info: "Store in a cool and dry place. Refrigeration is recommended to consume upto 2 months.",
    promise: ["Authentic Punjabi taste, premium ingredients and homemade goodness in every bite."] },
  { id: "sampooran-laddu", name: "Sampooran Laddu", cat: "sweetness-with-wellness", price: 220, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 86, tags: ["sugar-free"], photo: "../../assets/sampooran-laddu.png",
    desc: "A wholesome blend of seeds, nuts and Ayurvedic herbs bound in jaggery — nourishment in every bite.",
    facts: ["Seeds & Nuts","Herb-Infused","Preservative-Free"],
    variants: [{"weight":"100 GM","price":220,"mrp":350},{"weight":"250 GM","price":450,"mrp":600},{"weight":"500 GM","price":850,"mrp":1200},{"weight":"1 KG","price":1650,"mrp":2200}],
    long_desc: "A traditional homemade laddu prepared with whole wheat atta, edible gond, nuts, seeds, pure desi ghee, and refined sugar–free Mishri powder. Rich in natural energy and nourishment, it supports strength, stamina, and overall wellness for all age groups.\n✔️ Refined sugar–free\n✔️ Made with desi ghee\n✔️ No preservatives\n✔️ Traditional homemade recipe",
    wellness_benefits: [{"text":"","title":"•\tProvides wholesome nourishment •\tSupports daily energy needs •\tContains naturally occurring nutrients from diverse ingredients •\tHelps make snacking more satisfying •\tA nourishing traditional sweet for the entire family"}],
    ingredients: ["A carefully balanced combination of wholesome traditional ingredients like gond, Whole Wheat Atta, Desi Ghee, Mishri Powder or jaggary, Almonds, Cashews, Walnuts, Raisins, Pumpkin Seeds, Sunflower Seeds, melon seeds, watermelon seeds, Sesame Seeds, Flax Seeds and spices like white and black pepper, nutmeg to flavour."],
    storage_info: "Keep in an airtight container in a cool, dry and hygienic place. Protect from moisture and direct sunlight. Can be consumed upto 3 months, if refrigerated.",
    promise: ["Wholesome ingredients, authentic preparation and uncompromised quality—crafted to bring traditional nourishment to your modern lifestyle."] },
  { id: "shakti-laddu", name: "Shakti Laddu", cat: "sweetness-with-wellness", price: 220, mrp: 350, weight: "100 GM", rating: 4.9, reviews: 128, tags: ["bestseller","sugar-free"], badge: "Bestseller", photo: "https://wiuokqmggxkonxvzrnsb.supabase.co/storage/v1/object/public/product-photos/shakti-laddu-1786079527965.png",
    desc: "Energy-rich laddu made with dry fruits, edible gum and jaggery — a traditional strength tonic with no refined sugar.",
    facts: ["No Refined Sugar","Dry Fruits & Gond","Daily Strength"],
    variants: [{"weight":"100 GM","price":220,"mrp":350},{"weight":"250 GM","price":450,"mrp":600},{"weight":"500 GM","price":850,"mrp":1200},{"weight":"1 KG","price":1650,"mrp":2200}],
    long_desc: "A wholesome blend of traditional ingredients crafted to naturally support your everyday energy and vitality. Shakti Laddu brings together the goodness of nuts, seeds, natural sweeteners and nourishing ingredients in every delicious bite.",
    wellness_benefits: [{"text":"","title":"•\tSupports natural energy and stamina •\tRich in healthy fats and essential nutrients •\tHelps provide sustained energy •\tA wholesome alternative to conventional sweets •\tPerfect for an active lifestyle"}],
    ingredients: ["Nourishing blend of","nuts like almonds, cashews, walnuts, raisins and","seeds like pumpkin seeds, flaxseeds, melon seeds, watermelon seeds, sesame seeds, sunflower seeds, poppy seeds.","Natural sweetener - unprocessed dates.","White and black pepper,","Ginger powder and","Nutmeg to boost immunity and flavour.","Cow’s pure ghee"],
    storage_info: "Store in an airtight container in a cool and dry place. Keep away from direct sunlight and moisture. Refrigerate in summers. Can consume till 6 months if refrigerated.",
    shelf_life: "6 months from the date of packaging",
    promise: ["Made with carefully selected ingredients, traditional wisdom and no compromise on quality. Every Mishthi Sattva product is crafted with love, purity and a focus on wholesome goodness."] },

  // ---- Sattvic Sip ----
  { id: "badam-milk", name: "Badam Milk", cat: "sip", price: 200, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A wholesome traditional Badam Milk premix made with the goodness of almonds and aromatic ingredients. Simply mix with warm or chilled milk to create a rich, creamy and nourishing drink.",
    facts: [],
    variants: [{"weight":"100 GM","price":200,"mrp":350}],
    long_desc: "A wholesome traditional Badam Milk premix made with the goodness of almonds and aromatic ingredients. Simply mix with warm or chilled milk to create a rich, creamy and nourishing drink.",
    wellness_benefits: [{"text":"","title":"•\tProvides nourishment from almonds  •\tNaturally rich and satisfying  •\tSupports everyday dietary nutrition  •\tDelicious option for children and adults"}],
    ingredients: ["Milk powder, almonds, cashews, seeds, mishri powder."],
    storage_info: "Store in an airtight container in a cool, dry place. Avoid moisture and direct sunlight.\nShelf Life: 3 months.",
    promise: ["Real Ingredients • Satvic • Homemade • No Preservatives • No Artificial Flavours • No Chemicals"] },
  { id: "herbal-heart-sip", name: "Herbal Heart Sip", cat: "sip", price: 200, mrp: 350, weight: "1 Month Pack", rating: 4.7, reviews: 54, tags: [], photo: "../../assets/herbal-heart-sip.png",
    desc: "A warming herbal infusion blended to support heart health and circulation. One pinch in hot water, daily.",
    facts: ["Heart-Friendly","Caffeine-Free","Herbal Blend"],
    variants: [{"weight":"1 Month Pack","price":200,"mrp":350}],
    long_desc: "A soothing Ayurvedic herbal infusion crafted with Arjun Chaal, Tulsi, Moringa, kesar, beetroot, coriander, Amla and warming spices. Herbal Heart Sip is a refreshing, caffeine-free beverage designed for mindful daily wellness.",
    wellness_benefits: [{"text":"","title":"•\tSupports everyday heart-conscious wellness  •\tRefreshing and naturally aromatic  •\tSupports comfortable digestion  •\tProvides antioxidant-rich herbs and spices  •\tNaturally caffeine-free"}],
    ingredients: ["Arjun Chaal, Tulsi, Amla, Dry Ginger, Green Cardamom and Kesar, as per variant."],
    storage_info: "Store in a cool, dry place away from moisture and direct sunlight. Keep container tightly closed after every use.\nShelf Life: 6 months from the date of manufacture.",
    promise: ["100% Satvic • Homemade • No Preservatives • No Refined Sugar • No Chemicals • No Refined Oil • No Caffeine"] },
  { id: "hing-pickle", name: "Hing Pickle", cat: "sip", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A unique traditional pickle enriched with the distinctive aroma and flavour of hing. Bold, aromatic and deeply flavourful, it adds a special touch to everyday Indian meals.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1KG","price":500,"mrp":700}],
    long_desc: "A unique traditional pickle enriched with the distinctive aroma and flavour of hing. Bold, aromatic and deeply flavourful, it adds a special touch to everyday Indian meals.",
    wellness_benefits: [{"text":"","title":"•\tInspired by traditional Indian culinary ingredients •\tAdds distinctive flavour and aroma to meals •\tMade with carefully selected spices •\tA unique addition to your achar collection"}],
    ingredients: ["Hing and carefully selected raw mangoes, spices, oil and salt according to the Mishthi Sattva recipe."],
    storage_info: "Store in a cool and dry place. Always use a clean and dry spoon.",
    promise: ["Distinctive traditional flavours, premium ingredients and authentic recipes crafted with care."] },
  { id: "jaljeera-sattu", name: "Jaljeera Sattu", cat: "sip", price: 260, mrp: 400, weight: "500 GM", rating: 4.8, reviews: 27, tags: ["new"], photo: "../../assets/jaljeera-sattu.png",
    desc: "A cooling pudina-jaljeera sattu blend — instant, tasty and rich in protein. Just add water.",
    facts: ["Cooling Pudina","Rich in Protein","Instant & Tasty"],
    variants: [{"weight":"500 GM","price":260,"mrp":400}],
    long_desc: "A refreshing traditional Sattu-based beverage mix blended with aromatic herbs and spices. Jaljeera Sattu combines the nourishing character of Sattu with a tangy, refreshing Indian flavour.",
    wellness_benefits: [{"text":"","title":"•\tRefreshing and satisfying  •\tHelps make a nourishing summer beverage  •\tTraditionally used spices support digestion  •\tProvides plant-based nutrition from Sattu"}],
    ingredients: ["Roasted channa and jau, nuts, seeds and roasted jeera powder, white & black salt, hing and other Ayurvedic spices."],
    storage_info: "Store in an airtight container in a cool, dry place. Keep away from moisture.\nShelf Life: 3 months.",
    promise: ["Satvic • Homemade • Traditional Ingredients • No Preservatives • No Artificial Colours • No Chemicals"] },
  { id: "kesar-milk", name: "Kesar Milk", cat: "sip", price: 200, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A luxurious traditional milk beverage infused with the delicate aroma of Kesar and carefully selected natural ingredients. Kesar Milk is perfect for a comforting bedtime drink, festive occasions or everyday indulgence.",
    facts: [],
    variants: [{"weight":"100 GM","price":200,"mrp":350}],
    long_desc: "A luxurious traditional milk beverage infused with the delicate aroma of Kesar and carefully selected natural ingredients. Kesar Milk is perfect for a comforting bedtime drink, festive occasions or everyday indulgence.",
    wellness_benefits: [{"text":"","title":"•\tNourishing and comforting  •\tNaturally aromatic  •\tA delicious way to enjoy warm milk  •\tPerfect for children and adults when suitable for their dietary needs"}],
    ingredients: ["Kesar, Milk powder, almonds, cashews, seeds, mishri powder."],
    storage_info: "Store in a cool, dry place in an airtight container.\nShelf Life: 3 months.",
    promise: ["Premium Ingredients • Satvic • Homemade • No Preservatives • No Artificial Colours • No Chemicals"] },
  { id: "mojito-powder", name: "Mojito Powder", cat: "sip", price: 200, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A refreshing instant beverage mix crafted to create a vibrant minty and citrus-inspired drink at home. Simply mix with chilled water, add ice and enjoy a refreshing homemade-style beverage.",
    facts: [],
    variants: [{"weight":"100 GM","price":200,"mrp":350}],
    long_desc: "A refreshing instant beverage mix crafted to create a vibrant minty and citrus-inspired drink at home. Simply mix with chilled water, add ice and enjoy a refreshing homemade-style beverage.",
    wellness_benefits: [{"text":"","title":"•\tRefreshing and cooling beverage option  •\tConvenient instant preparation  •\tGreat for summer gatherings and celebrations  •\tDelicious alternative to packaged soft drinks"}],
    ingredients: ["Dry Mint Powder, Lemon Peel Powder, Roasted Cumin, Black Salt & Rock Salt, Dry Ginger Powder, Fennel Powder, Black Pepper Powder, Amchur ."],
    storage_info: "Store in a cool, dry place in an airtight container. Protect from moisture.\nShelf Life: 3 months.",
    promise: ["Satvic • Homemade • No Preservatives • No Artificial Colours* • No Chemicals"] },
  { id: "protein-sattu", name: "Protein Sattu Drink", cat: "sip", price: 260, mrp: 400, weight: "500 GM", rating: 4.7, reviews: 61, tags: ["new"], badge: "New", photo: "../../assets/protein-sattu.png",
    desc: "Roasted gram sattu, naturally high in protein and fibre. Mix sweet or savoury for an instant cooling drink.",
    facts: ["Plant Protein","Cooling","No Additives"],
    variants: [{"weight":"500 GM","price":260,"mrp":400}],
    long_desc: "A wholesome traditional Indian protein drink mix made with nourishing roasted ingredients. Protein Sattu is a convenient, natural way to add plant-based nutrition to your daily routine.",
    wellness_benefits: [{"text":"","title":"•\tHelps supplement daily protein intake  •\tProvides nourishing plant-based nutrition  •\tSupports sustained energy  •\tTraditionally enjoyed as a filling beverage  •\tSuitable for an active lifestyle"}],
    ingredients: ["Roasted channa and jau, nuts, seeds and jaggery powder."],
    storage_info: "Store in an airtight container in a cool, dry place. Protect from moisture.\nShelf Life: 3 months.",
    promise: ["Satvic • Homemade • Natural Ingredients • No Preservatives • No Refined Sugar • No Chemicals"] },
  { id: "shahi-sip-scoop", name: "Shahi Sip & Scoop", cat: "sip", price: 200, mrp: 350, weight: "100 GM", rating: 4.9, reviews: 19, tags: ["new"], badge: "New", photo: "../../assets/shahi-sip-scoop.png",
    desc: "A badam-milk premix that doubles as ice cream — drink it, freeze it, love it. No artificial creamers.",
    facts: ["Badam Milk & Ice Cream","No Artificial Creamers","Just Add Milk"],
    variants: [{"weight":"100 GM","price":200,"mrp":350}],
    long_desc: "A delightful Mishthi Sattva premix created to bring together the richness of Shahi Milk Badam and the joy of homemade desserts. Use it to prepare a luxurious milk drink or delicious homemade ice cream.",
    wellness_benefits: [{"text":"","title":"•\tProvides nourishment from milk and nuts  •\tNaturally aromatic and indulgent  •\tConvenient preparation at home  •\tA versatile base for drinks and desserts"}],
    ingredients: ["Nuts, seeds, milk powder, makhana"],
    storage_info: "Store in a cool, dry place in an airtight container. Avoid moisture and direct sunlight.\nShelf Life: 3 months.",
    promise: ["Homemade Quality • Satvic • No Preservatives • No Artificial Flavours* • No Chemicals"] },
  { id: "shinkaji-masala", name: "Shinkaji Masala", cat: "sip", price: 200, mrp: 350, weight: "100 GM", rating: 4.7, reviews: 38, tags: [], photo: "../../assets/shinkaji-masala-pack.png",
    desc: "A robust homestyle blend for hearty Punjabi gravies and dals.",
    facts: ["Homestyle Blend","Rich Aroma","Small Batch"],
    variants: [{"weight":"100 GM","price":200,"mrp":350}],
    long_desc: "A refreshing traditional Indian Shikanji masala crafted with aromatic spices and natural ingredients. Just add to chilled water for an instant, flavourful summer drink.",
    wellness_benefits: [{"text":"","title":"•\tRefreshing and hydrating when prepared with water  •\tTraditional spices support digestion  •\tConvenient instant beverage preparation  •\tPerfect for hot summer days"}],
    ingredients: ["Jeera, white & black salt, black pepper, lemon extract."],
    storage_info: "Store tightly closed in a cool, dry place. Protect from moisture and sunlight.\nShelf Life: 3 months.",
    promise: ["Satvic • Homemade • No Preservatives • No Artificial Colours • No Chemicals"] },
  { id: "soup-premix", name: "Soup premix", cat: "sip", price: 200, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A versatile homemade soup premix designed as a wholesome base for delicious soups. Use it to prepare comforting vegetable soup or create your own variations with seasonal vegetables and ingredients.",
    facts: [],
    variants: [{"weight":"100 GM","price":200,"mrp":350}],
    long_desc: "A versatile homemade soup premix designed as a wholesome base for delicious soups. Use it to prepare comforting vegetable soup or create your own variations with seasonal vegetables and ingredients.",
    wellness_benefits: [{"text":"","title":"•\tConvenient way to prepare a warm, comforting soup  •\tCan be paired with a variety of vegetables  •\tSuitable for everyday family meals  •\tContains carefully selected herbs, spices and nourishing ingredients"}],
    ingredients: ["Lentils, dry vegetables in powder form, spices."],
    storage_info: "Store in an airtight container in a cool, dry place. Protect from moisture and direct sunlight.\nShelf Life: 3 months.",
    promise: ["Homemade • Satvic • No Preservatives • No Refined Oil • No Artificial Colours • No Chemicals"] },
  { id: "thandai-premix", name: "Thandai Premix", cat: "sip", price: 200, mrp: 350, weight: "100 GM", rating: 4.9, reviews: 67, tags: ["new"], badge: "Seasonal", photo: "../../assets/protein-sattu.png",
    desc: "Almonds, fennel, rose and saffron, ground for a festive cooling thandai. Just add milk.",
    facts: ["Saffron & Rose","Festive Favourite","No Preservatives"],
    variants: [{"weight":"100 GM","price":200,"mrp":350}],
    long_desc: "A fragrant traditional Thandai premix prepared with carefully selected nuts, seeds, aromatic spices and natural ingredients. A festive favourite that can be transformed into a delicious chilled or warm beverage.",
    wellness_benefits: [{"text":"","title":"•\tNourishing and naturally rich in nuts and seeds  •\tAromatic traditional spices support digestion  •\tRefreshing and satisfying  •\tPerfect for festive occasions and family gatherings"}],
    ingredients: ["Nuts, seeds, rose petals, poppy seeds, fennel seeds."],
    storage_info: "Store airtight in a cool, dry place away from sunlight and moisture.\nShelf Life: 3 months.",
    promise: ["Traditional Taste • Satvic • Homemade • No Preservatives • No Artificial Colours • No Refined Sugar*","*Only if this matches your final formulation."] },

  // ---- Immunity Booster ----
  { id: "chyawanprash", name: "Chyawanprash", cat: "immunity", price: 600, mrp: 1000, weight: "500 GM", rating: 5, reviews: 214, tags: ["bestseller","sugar-free","new"], badge: "Featured", photo: "../../assets/chyawanprash.jpg",
    desc: "A modern take on the 5,000-year-old recipe — slow-cooked with amla, herbs and natural sweeteners. Zero refined sugar.",
    facts: ["Amla & 40+ Herbs","Supports Immunity","No Refined Sugar"],
    variants: [{"weight":"500 GM","price":600,"mrp":1000}],
    long_desc: "A traditional Ayurvedic herbal formulation prepared with carefully picked Amla, premium quality unprocessed dates and a carefully selected blend of herbs, spices and natural ingredients. Mishthi Sattva Chyawanprash is crafted in small batches with a focus on traditional preparation and wholesome nourishment which is completely sugar-free.",
    wellness_benefits: [{"text":"","title":"•\tSupports everyday immunity and wellness  •\tRich in naturally occurring antioxidants  •\tTraditionally used to support vitality and strength  •\tSupports general respiratory and digestive wellness  •\tA nourishing addition to a balanced daily routine"}],
    ingredients: ["Amla, unprocessed dates for sweetness, desi ghee for preservation,  traditional Ayurvedic herbs, spices and other natural ingredients as per the Mishthi Sattva formulation."],
    storage_info: "Store in a cool, dry place away from direct sunlight and moisture. Always use a clean, dry spoon and keep the container tightly closed.  Shelf Life: 3 months from the date of manufacture.",
    promise: ["Ayurvedic • Satvic • Homemade • No Preservatives • No Artificial Colours • No Chemicals • No Refined Oil • No Sugar Added"] },
  { id: "fix-and-fusion", name: "Fix and Fusion", cat: "immunity", price: 350, mrp: 500, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "Fit & Fusion is a thoughtfully crafted Ayurvedic-inspired wellness blend designed to complement a balanced diet and active lifestyle. Made with carefully selected herbs and traditional spices, it is created for individuals looking to support healthy weight management naturally.",
    facts: [],
    variants: [{"weight":"100 GM","price":350,"mrp":500}],
    long_desc: "Fit & Fusion is a thoughtfully crafted Ayurvedic-inspired wellness blend designed to complement a balanced diet and active lifestyle. Made with carefully selected herbs and traditional spices, it is created for individuals looking to support healthy weight management naturally.",
    wellness_benefits: [{"text":"","title":"•\tSupports healthy weight-management goals  •\tComplements a balanced diet and regular physical activity  •\tSupports healthy digestion and metabolism  •\tHelps make a mindful pre-meal wellness routine  •\tMade with traditional herbs and spices"}],
    ingredients: ["Saunf, Jeera, Ajwain, Coriander Seeds, Methi Seeds, Cinnamon, Sonth, Giloy Powder, Black Pepper"],
    storage_info: "Store in a cool, dry place away from moisture and direct sunlight. Keep tightly closed after every use. Shelf Life: 3 months from the date of manufacture.",
    promise: ["Ayurvedic • Satvic • Homemade • No Preservatives • No Refined Sugar • No Chemicals • No Refined Oil"] },
  { id: "nitya-poshan-formula-kids", name: "Nitya Poshan Formula- Kids", cat: "immunity", price: 750, mrp: 1100, weight: "500 GM", rating: 4.8, reviews: 0, tags: ["new"], badge: "New", photo: "https://wiuokqmggxkonxvzrnsb.supabase.co/storage/v1/object/public/product-photos/nitya-poshan-formula-kids-1784983057177.png",
    desc: "A wholesome daily protein powder made for growing kids — clean nutrition from our kitchen.",
    facts: ["For Kids","Daily Nutrition","No Additives"],
    variants: [{"weight":"500 GM","price":750,"mrp":1100}],
    long_desc: "Nitya Poshan Formula – Kids is a wholesome nutritional blend created to complement children's everyday diet. Made with carefully selected nourishing ingredients, it is designed as a convenient addition to milk, smoothies or other suitable foods.",
    wellness_benefits: [{"text":"","title":"•\tHelps complement children's daily nutritional needs  •\tProvides protein and other essential nutrients  •\tSupports everyday energy and nourishment  •\tA convenient addition to milk or breakfast  •\tMade with wholesome, carefully selected ingredients"}],
    ingredients: ["Selected Nuts, seeds, makhana, milk extract."],
    storage_info: "Store in a cool, dry place in an airtight container. Protect from moisture and direct sunlight.\nShelf Life: 3 months from the date of manufacture.",
    promise: ["Wholesome • Satvic • Homemade • No Preservatives • No Artificial Colours • No Chemicals • No Refined Oil"] },
  { id: "nitya-poshan-formula-men", name: "Nitya Poshan Formula- Men", cat: "immunity", price: 750, mrp: 1100, weight: "500 GM", rating: 4.8, reviews: 0, tags: ["new"], badge: "New", photo: "https://wiuokqmggxkonxvzrnsb.supabase.co/storage/v1/object/public/product-photos/nitya-poshan-formula-men-1784983323822.png",
    desc: "A daily protein powder blend for men — wholesome nutrition to support everyday strength.",
    facts: ["For Men","Daily Nutrition","No Additives"],
    variants: [{"weight":"500 GM","price":750,"mrp":1100}],
    long_desc: "Nitya Poshan Formula – Men is a wholesome nutritional blend created to complement the daily nutritional needs of men. Prepared with carefully selected ingredients, it provides convenient everyday nourishment for an active lifestyle.",
    wellness_benefits: [{"text":"","title":"•\tHelps supplement daily protein intake  •\tSupports everyday energy and nourishment  •\tConvenient source of nutritional support  •\tSuitable for active daily routines  •\tMade with wholesome ingredients"}],
    ingredients: ["Selected Nuts, Seeds, makhana, ashwgandha, musli, and Ayurvedic Herbs."],
    storage_info: "Store in a cool, dry place in an airtight container. Keep away from moisture and direct sunlight.\nShelf Life: 3 months from the date of manufacture.",
    promise: ["Wholesome • Satvic • Homemade • No Preservatives • No Artificial Colours • No Chemicals • No Refined Oil"] },
  { id: "nitya-poshan-formula-women", name: "Nitya Poshan Formula- Women", cat: "immunity", price: 700, mrp: 1100, weight: "500 GM", rating: 4.8, reviews: 0, tags: ["new"], badge: "New", photo: "https://wiuokqmggxkonxvzrnsb.supabase.co/storage/v1/object/public/product-photos/nitya-poshan-formula-women-1784983223006.png",
    desc: "A daily protein powder blend for women — wholesome nutrition for everyday wellness.",
    facts: ["For Women","Daily Nutrition","No Additives"],
    variants: [{"weight":"500 GM","price":700,"mrp":1100}],
    long_desc: "Nitya Poshan Formula – Women is a wholesome nutritional blend designed to complement women's everyday diet. Crafted with carefully selected nourishing ingredients, it offers convenient daily nutrition in a simple and delicious form.",
    wellness_benefits: [{"text":"","title":"•\tHelps supplement daily protein and nutritional intake  •\tSupports everyday energy and nourishment  •\tConvenient for busy lifestyles, and regulates monthly cycles •\tCan be enjoyed with milk, smoothies or suitable foods  •\tMade with wholesome ingredients which supports back pains."}],
    ingredients: ["Selected Nuts, Seeds, makhana, Shatavri, ashwgandha, musli, and Ayurvedic Herbs."],
    storage_info: "Store in an airtight container in a cool, dry place. Protect from moisture, heat and direct sunlight.\nShelf Life: 3 months from the date of manufacture.",
    promise: ["Wholesome • Satvic • Homemade • No Preservatives • No Artificial Colours • No Chemicals • No Refined Oil"] },

  // ---- Sattvic Body Care ----
  { id: "kesh-vardaan-oil", name: "AyurKesh Vardaan Hair Oil", cat: "bodycare", price: 250, mrp: 350, weight: "100 ML", rating: 4.8, reviews: 74, tags: [], photo: "../../assets/kesh-vardaan-oil.png",
    desc: "An intensive hair-fall oil blend of bhringraj, brahmi, sesame and amaltas pods for thicker, stronger hair and to help reverse greying.",
    facts: ["Anti Hair-Fall","Brahmi & Bhringraj","Deep Nourishment"],
    variants: [{"weight":"100 ML","price":250,"mrp":350}],
    long_desc: "A nourishing hair oil inspired by traditional Ayurvedic hair-care rituals and crafted with carefully selected oils and botanical ingredients. Ayurkesh Vardaan Hair Oil brings the comfort of a traditional head massage into your modern self-care routine.",
    wellness_benefits: [{"text":"","title":"•\tHelps nourish the hair and scalp •\tSupports a healthy-looking hair appearance •\tProvides a comforting massage experience •\tHelps improve the feel of dryness when used as part of a regular hair-care routine •\tConsistency can provide grey hair reversal."}],
    ingredients: ["A carefully selected blend of nourishing oils like mustard, coconut, almond, sesame;  botanical extracts like shikakai, bhringraj, hibiscus, amaltas pods, methi, kalongi and traditional ingredients according to the Mishthi Sattva formulation."],
    storage_info: "Store in a cool and dry place away from direct sunlight. Keep the bottle tightly closed after use.",
    promise: ["Inspired by traditional hair-care wisdom and thoughtfully crafted with carefully selected ingredients for your everyday self-care ritual."],
    usage_info: "Take an appropriate amount of oil and gently massage into the scalp and through the lengths of the hair. Leave on for the desired duration (atleast two hours mendatory) and wash as per your regular hair-care routine." },
  { id: "kesh-vash-shampoo", name: "AyurKesh Wash", cat: "bodycare", price: 250, mrp: 350, weight: "100 GM", rating: 4.7, reviews: 88, tags: ["bestseller"], photo: "../../assets/kesh-vash-shampoo.png",
    desc: "A gentle herbal shampoo with shikakai and reetha — cleanses without stripping natural oils.",
    facts: ["Shikakai & Reetha","Sulphate-Free","Gentle Cleanse"],
    variants: [{"weight":"100 GM","price":250,"mrp":350}],
    long_desc: "A gentle, thoughtfully crafted hair cleansing formula in powder form inspired by the goodness of traditional botanical ingredients. Ayurkesh Wash is designed to cleanse the hair and scalp while leaving your hair feeling fresh, soft and naturally cared for.",
    wellness_benefits: [{"text":"","title":"•\tGently cleanses the hair and scalp •\tHelps remove everyday dirt and product build-up •\tLeaves hair feeling fresh and clean •\tSupports a soft and manageable hair feel •\tSuitable for regular hair-care routines"}],
    ingredients: ["A carefully selected blend of Ayurvedic herbs like Retha, Amla, Bhringraj, Curry leaves, Neem leaves, hibiscus flowers and leaves. Except it, some seeds like methi, kalonji, flaxseeds."],
    storage_info: "Store in a cool, dry place away from direct sunlight. Keep the zip lock tightly closed after use.",
    promise: ["Thoughtfully crafted with carefully selected ingredients and a focus on gentle, effective everyday hair care."],
    usage_info: "Soak a small amount of Ayurkesh wash powder in a 50 ml water in a glass bowl overnight. Morning, sieve the liquid through a cloth, add a small amount of any shampoo in it for worthy form consistency. Apply an appropriate amount to wet hair and scalp. Gently massage to create a lather and rinse." },
  { id: "glow-radiance-cream", name: "Glow Radiance Cream", cat: "bodycare", price: 350, mrp: 450, weight: "50 GM", rating: 4.7, reviews: 63, tags: ["bestseller"], photo: "../../assets/glow-radiance-cream-pack.png",
    desc: "A lightweight daily moisturiser with saffron and natural oils for soft, glowing skin.",
    facts: ["Saffron Infused","Daily Moisture","Non-Greasy"],
    variants: [{"weight":"50 GM","price":350,"mrp":450}],
    long_desc: "A luxurious daily skincare cream designed to provide lasting moisture and leave the skin feeling soft, smooth and naturally radiant. Glow Radiance Cream is a comforting addition to your everyday skincare ritual.",
    wellness_benefits: [{"text":"","title":"•\tHelps moisturise and nourish the skin •\tLeaves skin feeling soft and smooth •\tSupports a healthy-looking glow •\tProvides a comfortable, hydrated skin feel •\tSuitable for everyday skincare routines"}],
    ingredients: ["A carefully selected blend of moisturising ingredients like coconut oil, almond oil, desi cow ghee; botanical extracts like Aloevera, cucumber and turmeric, kesar threads; and other skin-loving components according to the Mishthi Sattva formulation."],
    storage_info: "Store in a cool and dry place away from direct sunlight. Keep the container tightly closed after use. Or keep it in your fridge, because of the absence of any kind of preservative or any chemical.",
    promise: ["Thoughtfully formulated with carefully selected ingredients to bring nourishment, comfort and a natural-looking a baby-like glow to your skincare routine."],
    usage_info: "Apply an appropriate amount to clean skin and gently massage until absorbed. Use as part of your daily skincare routine." },
  { id: "glow-radiance-soap", name: "Glow Radiance Soap", cat: "bodycare", price: 100, mrp: 200, weight: "1 Piece", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A thoughtfully crafted cleansing bar designed to gently cleanse the skin while providing a fresh and comforting bathing experience. Glow Radiance Soap combines everyday cleansing with the care of carefully selected completely natural ingredients.",
    facts: [],
    variants: [{"weight":"1 Piece","price":100,"mrp":200}],
    long_desc: "A thoughtfully crafted cleansing bar designed to gently cleanse the skin while providing a fresh and comforting bathing experience. Glow Radiance Soap combines everyday cleansing with the care of carefully selected completely natural ingredients.",
    wellness_benefits: [{"text":"","title":"•\tGently cleanses the skin •\tHelps remove everyday impurities •\tLeaves the skin feeling fresh and clean •\tSupports a soft and comfortable skin feel •\tMakes everyday bathing a refreshing experience"}],
    ingredients: ["A carefully selected blend of cleansing ingredients, botanical extracts such as lemon peel, orange peel, aleovera; and skin-conditioning components according to the Mishthi Sattva formulation."],
    storage_info: "Store in a cool, dry place. Allow the soap to dry between uses for best longevity.",
    promise: ["Thoughtfully crafted with carefully selected ingredients to make everyday cleansing gentle, refreshing and enjoyable."],
    usage_info: "Apply to wet skin and gently work into a lather. Rinse thoroughly with water." },
  { id: "urban-glow", name: "Instant Ubtan Glow", cat: "bodycare", price: 200, mrp: 350, weight: "100 GM", rating: 4.6, reviews: 52, tags: ["new"], badge: "New", photo: "../../assets/ubtan-glow-pack.png",
    desc: "A brightening face pack for an instant, natural radiance — perfect before an occasion.",
    facts: ["Instant Radiance","Natural Actives","All Skin Types"],
    variants: [{"weight":"100 GM","price":200,"mrp":350}],
    long_desc: "blend designed to gently cleanse and refresh the skin. It brings the beauty of traditional Inspired by the timeless Indian tradition of ubtan, Instant Glow Ubtan is a refreshing skincare skincare rituals into a simple and convenient modern format.",
    wellness_benefits: [{"text":"","title":"•\tGently cleanses and refreshes the skin •\tHelps remove everyday surface impurities •\tLeaves the skin feeling soft and smooth •\tSupports a fresh and naturally radiant-looking appearance •\tInspired by traditional ubtan skincare rituals"}],
    ingredients: ["A thoughtfully selected blend of traditional ubtan-inspired ingredients besan, rice, oats; botanical components like orange peel, mulathi powder; and other skin-loving ingredients according to the Mishthi Sattva formulation."],
    storage_info: "Store in a cool and dry place. Keep the container tightly closed and protect the product from moisture.",
    promise: ["Inspired by traditional Indian beauty rituals and thoughtfully crafted with carefully selected ingredients for a refreshing modern skincare experience."],
    usage_info: "Apply according to the recommended instructions for your specific formulation. Gently massage onto damp skin if applicable, then rinse thoroughly." },
  { id: "vitamin-c-serum", name: "Vitamin C Serum", cat: "bodycare", price: 200, mrp: 300, weight: "100 Ml", rating: 4.8, reviews: 91, tags: ["bestseller","new"], photo: "../../assets/vitamin-c-serum-pack.png",
    desc: "A brightening vitamin C serum that evens tone and adds a healthy glow over time.",
    facts: ["Brightening","Evens Tone","Lightweight"],
    variants: [{"weight":"100 Ml","price":200,"mrp":300}],
    long_desc: "A lightweight facial serum designed to complement your everyday skincare routine and support the appearance of brighter, refreshed and healthy-looking skin. Its easy-to-apply texture makes it a simple addition to your daily glow ritual with its mist spray bottle.",
    wellness_benefits: [{"text":"","title":"•\tSupports the appearance of bright and radiant-looking skin •\tHelps improve the appearance of dull-looking skin •\tProvides a lightweight skincare experience •\tHelps promote a refreshed and healthy-looking appearance •\tEasy to layer into your daily skincare routine"}],
    ingredients: ["Formulated with Vitamin C and other carefully selected skin-loving ingredients like rose water, rice and mulethi."],
    storage_info: "Store in a cool, dry place away from direct sunlight. Keep the bottle tightly closed when not in use and keep it in fridge because of absence of any chemical or preservative.",
    promise: ["Thoughtfully formulated with carefully selected ingredients and a focus on creating simple, effective and enjoyable skincare rituals."],
    usage_info: "Apply one or two sprays direct on face, dry skin and gently massage or pat until absorbed. Follow with a moisturiser. No need to use sunscreen during daytime skincare routines." },

  // ---- Masala & Premix ----
  { id: "chat-masala", name: "Chat Masala", cat: "masala-premix", price: 200, mrp: 350, weight: "100 GM", rating: 4.8, reviews: 143, tags: ["bestseller"], photo: "../../assets/chat-masala.png",
    desc: "Tangy, zesty and freshly ground — the finishing touch for fruits, chaats and snacks.",
    facts: ["Freshly Ground","Tangy & Zesty","No Colour Added"],
    variants: [{"weight":"100 GM","price":200,"mrp":350}],
    long_desc: "A tangy, aromatic and flavourful blend created to add an irresistible chatpata touch to your favourite foods. Digestive Chat Masala brings together carefully selected spices and traditional ingredients for a delicious burst of flavour.",
    wellness_benefits: [{"text":"","title":"•\tMade with traditional aromatic spices •\tAdds a tangy and flavourful touch to everyday foods •\tCan be enjoyed with fruits, salads, chaats and snacks •\tInspired by the traditional use of digestive spices which helps in gas and bloating"}],
    ingredients: ["A carefully balanced blend of selected spices like white & black salt, black pepper, ginger, hing,fennel; herbs like jeera, podina, ajwain, maga, pipli; tangy ingredients like thikri noshadar, mango; and other flavourful components according to the Mishthi Sattva recipe."],
    storage_info: "Store in an airtight container in a cool and dry place. Keep away from moisture and always use a clean, dry spoon.",
    promise: ["Authentic flavours, carefully balanced spices and premium-quality ingredients in every sprinkle."] },
  { id: "garlic-seasoning", name: "Garlic Seasoning", cat: "masala-premix", price: 150, mrp: 300, weight: "50 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A rich and aromatic seasoning created for garlic lovers. Our Garlic Seasoning adds a delicious savoury flavour and irresistible aroma to snacks, vegetables, breads and a variety of everyday dishes.",
    facts: [],
    variants: [{"weight":"50 GM","price":150,"mrp":300}],
    long_desc: "A rich and aromatic seasoning created for garlic lovers. Our Garlic Seasoning adds a delicious savoury flavour and irresistible aroma to snacks, vegetables, breads and a variety of everyday dishes.",
    wellness_benefits: [{"text":"","title":"•\tAdds rich and aromatic flavour to meals •\tConvenient and easy to use •\tA versatile addition to everyday cooking •\tMakes simple dishes more flavourful"}],
    ingredients: ["Garlic and a carefully balanced blend of herbs, spices and other selected ingredients according to the Mishthi Sattva recipe."],
    storage_info: "Store in an airtight container in a cool and dry place. Keep away from moisture and direct sunlight.",
    promise: ["Rich flavour, carefully selected ingredients and everyday versatility in every sprinkle."] },
  { id: "pav-bhaji-masala", name: "Pav Bhaji Masala", cat: "masala-premix", price: 150, mrp: 300, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A bold and aromatic spice blend created to bring the authentic flavour of Mumbai-style pav bhaji to your kitchen. Rich, flavourful and perfectly balanced for creating delicious street-food favourites at home.",
    facts: [],
    variants: [{"weight":"100 GM","price":150,"mrp":300}],
    long_desc: "A bold and aromatic spice blend created to bring the authentic flavour of Mumbai-style pav bhaji to your kitchen. Rich, flavourful and perfectly balanced for creating delicious street-food favourites at home.",
    wellness_benefits: [{"text":"","title":"•\tMade with carefully selected spices •\tAdds authentic flavour and aroma to dishes •\tConvenient for preparing flavourful meals at home •\tBrings the taste of Indian street food to your kitchen"}],
    ingredients: ["A carefully balanced blend of aromatic Indian spices and flavourful ingredients according to the Mishthi Sattva recipe."],
    storage_info: "Store in a cool, dry place in an airtight container. Keep away from moisture and direct sunlight.",
    promise: ["Bold flavours, carefully selected spices and authentic street-food inspiration in every serving."] },
  { id: "peri-peri-masala", name: "Peri-Peri Masala", cat: "masala-premix", price: 150, mrp: 300, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A bold, zesty and flavourful seasoning created for those who love an exciting burst of taste. Peri Peri Masala adds a delicious spicy and tangy twist to snacks, fries, popcorn and everyday meals.",
    facts: [],
    variants: [{"weight":"100 GM","price":150,"mrp":300}],
    long_desc: "A bold, zesty and flavourful seasoning created for those who love an exciting burst of taste. Peri Peri Masala adds a delicious spicy and tangy twist to snacks, fries, popcorn and everyday meals.",
    wellness_benefits: [{"text":"","title":"•\tAdds bold flavour to everyday foods •\tMakes simple snacks more exciting •\tConvenient and easy to use •\tA versatile seasoning for multiple dishes"}],
    ingredients: ["A carefully balanced blend of spices, herbs and tangy flavourful ingredients according to the Mishthi Sattva recipe."],
    storage_info: "Store in an airtight container in a cool and dry place. Keep away from moisture.",
    promise: ["Bold flavours, carefully balanced ingredients and premium quality in every sprinkle."] },
  { id: "sambhar-masala", name: "Sambhar Masala", cat: "masala-premix", price: 150, mrp: 300, weight: "100 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "An aromatic South Indian-inspired spice blend created to bring rich, comforting and authentic flavours to your homemade sambar. Carefully balanced for aroma, depth and delicious everyday cooking.",
    facts: [],
    variants: [{"weight":"100 GM","price":150,"mrp":300}],
    long_desc: "An aromatic South Indian-inspired spice blend created to bring rich, comforting and authentic flavours to your homemade sambar. Carefully balanced for aroma, depth and delicious everyday cooking.",
    wellness_benefits: [{"text":"","title":"•\tMade with traditional aromatic spices •\tAdds authentic flavour to South Indian dishes •\tContains carefully selected herbs and spices •\tPerfect for everyday home cooking"}],
    ingredients: ["A carefully balanced blend of traditional spices, lentils and other flavourful ingredients according to the Mishthi Sattva recipe."],
    storage_info: "Store in an airtight container in a cool and dry place. Protect from moisture and direct sunlight.",
    promise: ["Authentic regional flavours and carefully selected ingredients blended to bring traditional taste to your kitchen."] },
  { id: "shahi-garam-masala", name: "Shahi Garam Masala", cat: "masala-premix", price: 120, mrp: 250, weight: "50 GM", rating: 4.9, reviews: 112, tags: ["bestseller"], photo: "../../assets/shahi-garam-masala.png",
    desc: "A royal garam masala of whole spices roasted and stone-ground for deep, layered warmth.",
    facts: ["Whole Spices","Roasted & Ground","Aromatic"],
    variants: [{"weight":"50 GM","price":120,"mrp":250}],
    long_desc: "A rich and aromatic blend of traditional Indian spices, carefully balanced to bring warmth, depth and authentic flavour to your favourite dishes. Garam Masala is an essential addition to every flavourful Indian kitchen.",
    wellness_benefits: [{"text":"","title":"•\tMade with traditional aromatic spices •\tAdds depth and warmth to meals •\tContains naturally flavourful herbs and spices •\tHelps create authentic Indian culinary experiences"}],
    ingredients: ["A carefully selected blend of traditional whole spices like jeera, coriander, long, elaichi, nutmeg, javitri, rose petals, cashews, seeds, dalchini and many more; roasted and ground according to the Mishthi Sattva recipe."],
    storage_info: "Store in an airtight container in a cool and dry place, away from direct sunlight and moisture",
    promise: ["Carefully selected spices, authentic blending and rich aroma in every spoonful."] },

  // ---- Munching ----
  { id: "chakhna-makhna", name: "Chakhna-Makhna", cat: "munching", price: 350, mrp: 500, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A bold, crunchy and flavour-packed munching mix created for those who love exciting Indian-inspired snacks. Chakhna Makhna brings together premium makhana and carefully selected ingredients with irresistible seasonings.",
    facts: [],
    variants: [{"weight":"500 GM","price":350,"mrp":500}],
    long_desc: "A bold, crunchy and flavour-packed munching mix created for those who love exciting Indian-inspired snacks. Chakhna Makhna brings together premium makhana and carefully selected ingredients with irresistible seasonings.",
    wellness_benefits: [{"text":"","title":"•\tMade with the goodness of nuts •\tA satisfying crunchy snack •\tBold and flavourful for enjoyable munching •\tPerfect for sharing and snack-time moments •\tBest combination with cocktails and mocktails"}],
    ingredients: ["Peanuts, green peas, Roasted channa; spices, herbs and flavourful seasonings according to the Mishthi Sattva recipe."],
    storage_info: "Store in an airtight container in a cool and dry place. Protect from moisture to maintain freshness and crunch.",
    promise: ["Premium ingredients, bold flavours and satisfying crunch—crafted to make every munching moment more exciting."] },
  { id: "namkeen-mix", name: "Healthy Murmura Namkeen Mix", cat: "munching", price: 300, mrp: 600, weight: "500 GM", rating: 4.6, reviews: 72, tags: [], photo: "../../assets/namkeen-mix.png",
    desc: "Roasted, never fried — a guilt-free namkeen made with millets, lentils and gentle spices.",
    facts: ["Roasted not Fried","No Refined Oil","High Fibre"],
    variants: [{"weight":"500 GM","price":300,"mrp":600},{"weight":"1 KG","price":600,"mrp":850}],
    long_desc: "A light, crunchy and flavourful namkeen mix made for everyday munching. Healthy Murmura Namkeen Mix brings together the satisfying crunch of murmura with carefully selected ingredients and delicious seasonings.",
    wellness_benefits: [{"text":"","title":"•\tLight and satisfying snack option •\tMade with carefully selected ingredients •\tOffers a delightful crunchy experience •\tPerfect for tea-time and everyday munching"}],
    ingredients: ["Murmura, selected nuts and seeds, roasted channa; spices and seasonings according to the Mishthi Sattva recipe."],
    storage_info: "Store in an airtight container in a cool and dry place to maintain freshness and crunchiness.",
    promise: ["Thoughtfully selected ingredients, delicious flavours and satisfying crunch in every handful."] },
  { id: "kurmure", name: "Kurmure", cat: "munching", price: 200, mrp: 350, weight: "250 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A classic crunchy favourite made for simple and satisfying munching. Our Kurmure bring together light texture, delightful crispiness and delicious flavours for an enjoyable snacking experience.",
    facts: [],
    variants: [{"weight":"250 GM","price":200,"mrp":350}],
    long_desc: "A classic crunchy favourite made for simple and satisfying munching. Our Kurmure bring together light texture, delightful crispiness and delicious flavours for an enjoyable snacking experience.",
    wellness_benefits: [{"text":"","title":"•\tLight and crunchy snack •\tConvenient for everyday munching •\tA satisfying option for tea-time and sharing •\tMade with carefully selected ingredients"}],
    ingredients: ["Rice, selected spices, seasonings and other components according to the Mishthi Sattva recipe."],
    storage_info: "Store in an airtight container or tightly sealed pack in a cool and dry place to maintain crispness.",
    promise: ["Simple ingredients, delicious flavours and satisfying crunch for everyday snacking."] },
  { id: "potato-chips", name: "Potato Chips", cat: "munching", price: 200, mrp: 350, weight: "250 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "Crispy, flavourful and irresistibly satisfying, our Potato Chips are made for those moments when only a perfect crunch will do. A delicious snack with carefully balanced seasoning in every bite.",
    facts: [],
    variants: [{"weight":"250 GM","price":200,"mrp":350}],
    long_desc: "Crispy, flavourful and irresistibly satisfying, our Potato Chips are made for those moments when only a perfect crunch will do. A delicious snack with carefully balanced seasoning in every bite.",
    wellness_benefits: [{"text":"","title":"•\tA satisfying crunchy snack •\tMade with carefully selected ingredients •\tPerfect for snacking and sharing •\tAvailable as a delicious everyday treat"}],
    ingredients: ["Potatoes, cooking oil, selected seasonings and other ingredients according to the Mishthi Sattva recipe."],
    storage_info: "Store in a cool and dry place. Keep the pack tightly sealed after opening to maintain freshness and crunch.",
    promise: ["Quality ingredients, satisfying crunch and delicious flavour in every bite."] },
  { id: "premium-makhana-mixture", name: "Premium Makhana Mixture", cat: "munching", price: 500, mrp: 700, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A deliciously crunchy and premium snack blend featuring the wholesome goodness of makhana. Carefully combined with selected ingredients and flavourful seasonings, it makes every munching moment special.",
    facts: [],
    variants: [{"weight":"500 GM","price":500,"mrp":700}],
    long_desc: "A deliciously crunchy and premium snack blend featuring the wholesome goodness of makhana. Carefully combined with selected ingredients and flavourful seasonings, it makes every munching moment special.",
    wellness_benefits: [{"text":"","title":"•\tMade with the goodness of makhana •\tLight and crunchy snacking experience •\tA satisfying alternative for mindful munching •\tMade with carefully selected ingredients"}],
    ingredients: ["Makhana, selected nuts & seeds, spices, seasonings and other components according to the Mishthi Sattva recipe."],
    storage_info: "Store in an airtight container in a cool and dry place. Protect from moisture to maintain crispness.",
    promise: ["Premium ingredients, satisfying crunch and carefully balanced flavours in every bite."] },
  { id: "rice-chips", name: "Rice Chips", cat: "munching", price: 200, mrp: 350, weight: "250 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "Light, crispy and deliciously satisfying, our Rice Chips offer a delightful crunch with carefully balanced flavours. A perfect snack for everyday munching and sharing.",
    facts: [],
    variants: [{"weight":"250 GM","price":200,"mrp":350}],
    long_desc: "Light, crispy and deliciously satisfying, our Rice Chips offer a delightful crunch with carefully balanced flavours. A perfect snack for everyday munching and sharing.",
    wellness_benefits: [{"text":"","title":"•\tLight and crispy snack option •\tMade with rice-based ingredients •\tConvenient for everyday munching •\tA satisfying crunchy experience"}],
    ingredients: ["Rice-based ingredients, selected seasonings, cooking oil and other recipe-specific components."],
    storage_info: "Store in a cool, dry place and keep the pack tightly sealed after opening.",
    promise: ["Thoughtfully crafted for delicious flavour, satisfying crunch and enjoyable everyday munching."] },

  // ---- MS Special ----
  { id: "ice-cream-premix", name: "Ice Cream Premix", cat: "ms-special", price: 200, mrp: 500, weight: "100 g", rating: 4.9, reviews: 24, tags: ["new"], badge: "New", photo: "../../assets/ice-cream-premix.png",
    desc: "A rich, creamy ice-cream premix loaded with almonds, pistachios and cashews. Just add milk, churn and freeze.",
    facts: ["Made with All Nuts","Rich & Creamy","Just Add Milk"],
    long_desc: "A rich, creamy ice-cream premix loaded with almonds, pistachios and cashews. Just add milk, churn and freeze." },

  // ---- Handcrafted Pickles ----
  { id: "adrak-nimbu-mirchi-pickle", name: "Adrak Nimbu Mirchi Pickle", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A bold and refreshing combination of ginger, lemon and chillies, carefully blended with aromatic spices. This pickle delivers layers of tangy, spicy and distinctive flavours.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A bold and refreshing combination of ginger, lemon and chillies, carefully blended with aromatic spices. This pickle delivers layers of tangy, spicy and distinctive flavours.",
    wellness_benefits: [{"text":"","title":"•\tMade with ginger, lemon and traditional spices •\tAdds bold flavour to everyday meals •\tA delicious combination of tangy and spicy ingredients •\tInspired by traditional flavour combinations"}],
    ingredients: ["Ginger, lemon, chillies, selected spices, salt and other recipe-specific ingredients."],
    storage_info: "Store in a cool, dry place and always use a clean, dry spoon.",
    promise: ["Bold combinations, carefully selected ingredients and authentic traditional flavours."] },
  { id: "bhey-lotus-stem-pickle", name: "Bhey (Lotus Stem) Pickle", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A distinctive traditional pickle made with bhey (lotus stem) and aromatic Indian spices. Carefully prepared to preserve its unique flavour and create a delicious accompaniment for everyday meals.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A distinctive traditional pickle made with bhey (lotus stem) and aromatic Indian spices. Carefully prepared to preserve its unique flavour and create a delicious accompaniment for everyday meals.",
    wellness_benefits: [{"text":"","title":"•\tMade with carefully selected traditional ingredients •\tAdds distinctive flavour to meals •\tA unique addition to traditional Indian cuisine •\tCrafted using authentic pickling practices"}],
    ingredients: ["Bhey, selected spices, oil, salt and other ingredients according to the Mishthi Sattva recipe."],
    storage_info: "Store in a cool and dry place. Always use a clean, dry spoon and keep the container tightly closed.",
    promise: ["Traditional ingredients, authentic recipes and carefully balanced flavours in every jar."] },
  { id: "bitter-gourd-karela-achar", name: "Bitter Gourd (Karela) Achar", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 Gm", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A unique and flavourful pickle crafted with karela and aromatic spices. Carefully balanced to create a delicious combination of distinctive flavours and traditional achar goodness.",
    facts: [],
    variants: [{"weight":"500 Gm","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A unique and flavourful pickle crafted with karela and aromatic spices. Carefully balanced to create a delicious combination of distinctive flavours and traditional achar goodness.",
    wellness_benefits: [{"text":"","title":"•\tMade with karela and traditional spices •\tAdds variety and bold flavour to meals •\tCrafted using traditional pickling methods •\tA unique addition to your pickle collection"}],
    ingredients: ["Karela, selected spices, oil, salt and other ingredients according to the Mishthi Sattva recipe."],
    storage_info: "Store in a cool and dry place. Always use a clean and dry spoon.",
    promise: ["Unique traditional flavours, carefully selected ingredients and authentic homemade recipes."] },
  { id: "carrot-gajar-pickle", name: "Carrot (Gajar pickle)", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A crunchy and flavourful carrot pickle crafted with carefully selected spices and traditional ingredients. Its delicious combination of texture, tang and spice makes every meal more exciting.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A crunchy and flavourful carrot pickle crafted with carefully selected spices and traditional ingredients. Its delicious combination of texture, tang and spice makes every meal more exciting.",
    wellness_benefits: [{"text":"","title":"•\tMade with carrots and traditional spices •\tAdds colour and flavour to everyday meals •\tA crunchy and satisfying accompaniment •\tInspired by traditional homemade pickle recipes"}],
    ingredients: ["Carrots, selected spices, salt and other recipe-specific ingredients."],
    storage_info: "Store in a cool and dry place. Keep the container tightly closed and always use a clean, dry spoon.",
    promise: ["Fresh ingredients, traditional spices and authentic homemade flavours crafted with care."] },
  { id: "carrot-caulliflower-gajar-gobi-pickle", name: "Carrot Caulliflower (Gajar-Gobi)Pickle", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A delicious traditional combination of crunchy carrots and flavourful cauliflower, blended with aromatic spices for a vibrant and satisfying pickle experience.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A delicious traditional combination of crunchy carrots and flavourful cauliflower, blended with aromatic spices for a vibrant and satisfying pickle experience.",
    wellness_benefits: [{"text":"","title":"•\tMade with carefully selected vegetables •\tAdds flavour and variety to everyday meals •\tA delicious combination of traditional ingredients •\tInspired by homemade seasonal pickle recipes"}],
    ingredients: ["Carrots, cauliflower, selected spices, salt and other ingredients according to the Mishthi Sattva recipe."],
    storage_info: "Store in a cool and dry place. Always use a clean, dry spoon and keep the container tightly closed.",
    promise: ["Fresh seasonal ingredients, carefully selected spices and authentic homemade flavours."] },
  { id: "carrot-cauliflower-turnip-pickle", name: "Carrot-cauliflower-turnip Pickle", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A classic seasonal pickle combining the goodness of carrots, cauliflower and turnip with aromatic Indian spices. Vibrant, flavourful and delightfully textured, it brings the taste of traditional homemade winter achar to your table.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A classic seasonal pickle combining the goodness of carrots, cauliflower and turnip with aromatic Indian spices. Vibrant, flavourful and delightfully textured, it brings the taste of traditional homemade winter achar to your table.",
    wellness_benefits: [{"text":"","title":"•\tMade with a variety of selected vegetables •\tAdds colour, flavour and texture to meals •\tA delicious seasonal accompaniment •\tInspired by traditional homemade winter recipes"}],
    ingredients: ["Carrots, cauliflower, shalgam (turnip), selected spices, oil, salt, jaggary and other ingredients according to the Mishthi Sattva recipe."],
    storage_info: "Store in a cool and dry place. Keep the container tightly closed and always use a clean, dry spoon.",
    promise: ["Traditional seasonal recipes, carefully selected vegetables and authentic spices crafted with love and care."] },
  { id: "galgal-mirchi-pickle", name: "Galgal Mirchi Pickle", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A distinctive North Indian-inspired pickle featuring the unique tang of galgal combined with the bold heat of chillies and aromatic spices.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A distinctive North Indian-inspired pickle featuring the unique tang of galgal combined with the bold heat of chillies and aromatic spices.",
    wellness_benefits: [{"text":"","title":"•\tMade with traditional ingredients and spices •\tOffers a distinctive regional flavour experience •\tAdds bold taste to everyday meals •\tInspired by authentic North Indian pickling traditions"}],
    ingredients: ["Galgal, chillies, selected spices, oil, salt and other ingredients according to the recipe."],
    storage_info: "Store in a cool and dry place. Keep the container tightly sealed and use a clean, dry spoon.",
    promise: ["Celebrating authentic regional flavours with carefully selected ingredients and traditional recipes."] },
  { id: "garlic-pickle", name: "Garlic Pickle", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A rich and aromatic pickle made with garlic and a bold blend of traditional spices. Every spoonful delivers deep flavour, irresistible aroma and authentic achar goodness.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A rich and aromatic pickle made with garlic and a bold blend of traditional spices. Every spoonful delivers deep flavour, irresistible aroma and authentic achar goodness.",
    wellness_benefits: [{"text":"","title":"•\tMade with garlic and traditional spices •\tAdds rich flavour to everyday meals •\tA delicious and aromatic accompaniment •\tInspired by traditional Indian pickling recipes"}],
    ingredients: ["Garlic, selected spices, oil, salt and other recipe-specific ingredients."],
    storage_info: "Store in a cool, dry place. Keep the container tightly closed and always use a clean, dry spoon.",
    promise: ["Bold ingredients, aromatic spices and traditional flavours crafted with care."] },
  { id: "green-stuffed-mirchi", name: "Green Stuffed Mirchi", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A flavour-packed traditional pickle featuring green chillies generously filled with an aromatic blend of spices. Every bite offers a delicious balance of heat, texture and authentic Indian flavours.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A flavour-packed traditional pickle featuring green chillies generously filled with an aromatic blend of spices. Every bite offers a delicious balance of heat, texture and authentic Indian flavours.",
    wellness_benefits: [{"text":"","title":"•\tMade with traditional aromatic spices •\tAdds bold flavour to everyday meals •\tA satisfying spicy accompaniment •\tInspired by authentic stuffed chilli recipes"}],
    ingredients: ["Green chillies, selected stuffing spices, oil, salt and other ingredients according to the Mishthi Sattva recipe."],
    storage_info: "Store in a cool, dry place and always use a clean, dry spoon.",
    promise: ["Authentic recipes, carefully selected spices and rich traditional flavours."] },
  { id: "lemon-spicy", name: "Lemon Spicy", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A bold and flavourful pickle made with tangy lemons and aromatic Indian spices. Lemon Spicy Pickle delivers the perfect balance of citrusy tang and a satisfying spicy kick.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A bold and flavourful pickle made with tangy lemons and aromatic Indian spices. Lemon Spicy Pickle delivers the perfect balance of citrusy tang and a satisfying spicy kick.",
    wellness_benefits: [{"text":"","title":"•\tMade with traditional spices and lemons •\tAdds bold flavour to everyday meals •\tA tangy and spicy accompaniment •\tInspired by authentic Indian pickling traditions"}],
    ingredients: ["Lemon, selected spices, salt and other recipe-specific ingredients."],
    storage_info: "Store in a cool and dry place. Keep the container tightly closed and use a clean, dry spoon.",
    promise: ["Authentic spices, bold flavours and traditional recipes in every jar."] },
  { id: "lemon-sweet", name: "Lemon Sweet", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A delightful balance of tangy lemons and delicious sweetness, crafted using traditional pickling methods. Lemon Sweet Pickle brings a comforting combination of sweet, tangy and aromatic flavours to every meal.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A delightful balance of tangy lemons and delicious sweetness, crafted using traditional pickling methods. Lemon Sweet Pickle brings a comforting combination of sweet, tangy and aromatic flavours to every meal.",
    wellness_benefits: [{"text":"","title":"•\tMade with lemons and traditional ingredients •\tA flavourful accompaniment to everyday meals •\tCombines sweet and tangy flavours •\tInspired by traditional pickling practices"}],
    ingredients: ["Lemon, natural sweetening ingredients, selected spices, Mishthi Sattva’s Garam Masala and other ingredients according to the Mishthi Sattva recipe."],
    storage_info: "Store in a cool, dry place and keep the jar tightly closed. Always use a clean, dry spoon.",
    promise: ["Balanced flavours, carefully selected ingredients and traditional recipes crafted with care."] },
  { id: "mango-pickle", name: "Mango Pickle", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A timeless Indian favourite crafted with raw mangoes and a carefully balanced blend of traditional spices. Our Mango Pickle delivers bold flavours, rich aroma and the comforting taste of homemade achar.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A timeless Indian favourite crafted with raw mangoes and a carefully balanced blend of traditional spices. Our Mango Pickle delivers bold flavours, rich aroma and the comforting taste of homemade achar.",
    wellness_benefits: [{"text":"","title":"•\tMade with traditional spices and ingredients •\tAdds bold flavour to everyday meals •\tA delicious accompaniment to Indian cuisine •\tCrafted using time-honoured pickling traditions"}],
    ingredients: ["Raw mango, selected spices, oil, salt and other ingredients according to the Mishthi Sattva recipe."],
    storage_info: "Store in a cool, dry place. Always use a clean and dry spoon. Keep the jar tightly closed after use.",
    promise: ["Authentic ingredients, traditional recipes and bold homemade flavours in every spoonful."] },
  { id: "mix-pickle", name: "Mix Pickle", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A vibrant combination of carefully selected vegetables and ingredients, blended with aromatic spices to create a delicious medley of flavours. Every spoonful brings something exciting to your plate.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A vibrant combination of carefully selected vegetables and ingredients, blended with aromatic spices to create a delicious medley of flavours. Every spoonful brings something exciting to your plate.",
    wellness_benefits: [{"text":"","title":"•\tMade with a variety of selected ingredients •\tAdds colour and flavour to everyday meals •\tA delicious combination of traditional flavours •\tInspired by authentic mixed achar recipes"}],
    ingredients: ["Sattva A selection of vegetables, spices, oil, salt and other ingredients according to the Mishthi recipe."],
    storage_info: "Store in a cool, dry place and always use a clean and dry spoon.",
    promise: ["A delicious blend of traditional ingredients, bold spices and authentic homemade flavours.","Customer Reviews"] },
  { id: "nimbu-mirchi", name: "Nimbu Mirchi", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A classic combination of tangy lemon and fiery green chillies, blended with aromatic spices for a bold and exciting achar experience.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A classic combination of tangy lemon and fiery green chillies, blended with aromatic spices for a bold and exciting achar experience.",
    wellness_benefits: [{"text":"","title":"•\tMade with traditional spices and ingredients •\tAdds bold flavours to everyday meals •\tA delicious combination of tangy and spicy notes •\tInspired by traditional Indian recipes"}],
    ingredients: ["Lemon, green chillies, selected spices, salt and other ingredients according to the recipe."],
    storage_info: "Store in a cool and dry place. Always use a clean and dry spoon.",
    promise: ["Traditional flavour combinations, carefully selected ingredients and authentic homemade taste."] },
  { id: "red-stuffed-mirchi", name: "Red Stuffed Mirchi", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A bold and aromatic traditional pickle made with red chillies filled with a delicious blend of carefully selected spices. Rich in flavour and full of character, it is perfect for those who enjoy a spicy culinary experience.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1KG","price":500,"mrp":700}],
    long_desc: "A bold and aromatic traditional pickle made with red chillies filled with a delicious blend of carefully selected spices. Rich in flavour and full of character, it is perfect for those who enjoy a spicy culinary experience.",
    wellness_benefits: [{"text":"","title":"•\tMade with carefully selected spices •\tAdds bold flavour to meals •\tInspired by traditional stuffed chilli recipes •\tA delicious accompaniment to Indian cuisine"}],
    ingredients: ["Red chillies, selected stuffing spices, oil, salt and other recipe-specific ingredients."],
    storage_info: "Store in a cool, dry place. Keep the jar tightly closed and always use a clean, dry spoon.",
    promise: ["Traditional recipes, bold spices and authentic flavours crafted with care."] },
  { id: "sweet-mango-chutney", name: "Sweet Mango Chutney", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A deliciously sweet and tangy mango chutney crafted to bring a burst of fruity flavour to every meal. Rich, comforting and full of character, it is perfect as an accompaniment or dip.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A deliciously sweet and tangy mango chutney crafted to bring a burst of fruity flavour to every meal. Rich, comforting and full of character, it is perfect as an accompaniment or dip.",
    wellness_benefits: [{"text":"","title":"•\tMade with the goodness of mango •\tAdds delicious sweet and tangy flavour •\tA versatile accompaniment for meals and snacks •\tInspired by traditional Indian chutney recipes"}],
    ingredients: ["Mango, natural sweetening ingredients, selected spices and other recipe-specific ingredients"],
    storage_info: "Store in a cool and dry place. Keep the container tightly closed and use a clean, dry spoon",
    promise: ["Fruity flavours, carefully selected ingredients and traditional recipes crafted with care."] },
  { id: "teet-pickle", name: "Teet Pickle", cat: "pickle-murabba", price: 300, mrp: 450, weight: "500 GM", rating: 4.8, reviews: 0, tags: [], photo: "",
    desc: "A traditional pickle crafted with the distinctive flavour of teet and a carefully balanced blend of aromatic Indian spices. A unique regional taste experience for those who appreciate authentic homemade achar.",
    facts: [],
    variants: [{"weight":"500 GM","price":300,"mrp":450},{"weight":"1 KG","price":500,"mrp":700}],
    long_desc: "A traditional pickle crafted with the distinctive flavour of teet and a carefully balanced blend of aromatic Indian spices. A unique regional taste experience for those who appreciate authentic homemade achar.",
    wellness_benefits: [{"text":"","title":"•\tMade using traditional ingredients •\tOffers a distinctive regional flavour •\tAdds variety to everyday meals •\tInspired by traditional pickling practices"}],
    ingredients: ["Teet selected spices, oil and salt according to the Mishthi Sattva recipe."],
    storage_info: "Store in a cool, dry place and always use a clean and dry spoon.",
    promise: ["Authentic regional recipes, carefully selected ingredients and traditional flavours preserved with care."] },
];

window.MSShopData = { MS_CATEGORIES, MS_PRODUCTS };
